### ISSUE TITLE
IPMI_6 : Verify ipmitool output content

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#1]
Enhancement : check ipmitool output content from "mc info" & "mc guid"

Eg: 

- "Firmware Revision" in "mc info" commands

- "System GUID" in "mc guid"

File : https://github.com/ARM-software/sbmr-acs/blob/main/ipmi/test_ipmi_shell_inband_manager_info.robot#L24

**Comment by amrathesh** [comment]
Hi @gtossk2,

We have modified the test to verify the output of mc guid and info commands with help of regex.

Please review https://github.com/ARM-software/sbmr-acs/pull/14

Thanks & Regards,
ACS Team
