### ISSUE TITLE
Warning Message on robotframework 7.0

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#19]
Warning Message on robotframework. Some keywords were deprecated as seen below.

```
Singular section headers like '*** Test Case ***' are deprecated. Use plural format like '*** Test Cases ***' instead.

The '[Return]' setting is deprecated. Use the 'RETURN' statement instead.
```

**Comment by amrathesh** [comment]
Hi @gtossk2,

We have updated deprecated robot keywords with updated ones. 
Verified changes with robotframework 7.0 on Linux. 

Please review https://github.com/ARM-software/sbmr-acs/pull/21

Thanks & Regards,
ACS Team
