### ISSUE TITLE
M2_OOB : Set HTTPS session timeout before runnning Redfish OOB

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#2]
Each BMC might has different session timeout value in default. It is better to set a reasonable session timeout value before running Redfish OOB test. 

Reference : https://redfish.dmtf.org/schemas/v1/SessionService.v1_1_8.json

**Comment by edhay** [comment]
Hi @gtossk2 
Keeping in view the timeout due to network delay, we have increased the timeout value from 30s to 120s.
The solution is as below:
https://github.com/ARM-software/sbmr-acs/pull/13
Please review

**Comment by edhay** [comment]
The issue is resolved the and package with the solution is available here:
https://github.com/ARM-software/sbmr-acs/actions/runs/7581370630
