### ISSUE TITLE
SOL output log directory not consistent with config file

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#20]
SOL output log directory pre-defined under **./logs**  
However, if user change the default **--outputdir=logs** in config, then it will cause TC run failed due to no log directory.

SOL output log directory : https://github.com/ARM-software/sbmr-acs/blob/main/lib/resource.robot#L69
Default log directory : https://github.com/ARM-software/sbmr-acs/blob/main/config#L10

**Comment by amrathesh** [comment]
Hi @gtossk2, 

Fixed the logs directory issue in SOL tests by using ${OUTPUT DIR} variable. Please review.

Thanks,
System ACS team
