### ISSUE TITLE
Rule ID check list for SBMR-ACS

### ISSUE THREAD

**Issue by anncheng-arm** [ARM-software/sbmr-acs#30]
Hi Team, 

Do we have rule ID checklist for SBMR-ACS like this [bsa-acs checklist](https://github.com/ARM-software/bsa-acs/blob/main/docs/arm_bsa_testcase_checklist.rst) that we can let end-user/partner to know which SBMR rule id is being covered by sbmr-acs tool?

@gtossk2 for visibility.

**Comment by amrathesh** [comment]
Hi @anncheng-arm, 

We don't have a rule ID checklist for SBMR-ACS at the moment, but we plan to create one. Currently, you can check the [test_lists](https://github.com/ARM-software/sbmr-acs/tree/main/test_lists). In the meantime, we will work on the ID checklist. Thanks for bringing this up!

Thanks,
System Compliance Team, Arm

**Comment by amrathesh** [comment]
Hi @anncheng-arm 

We have compiled a sbmr-acs test checklist, providing current SBMR coverage provided by the ACS. 
Please provide your review for #31 

Regards,
ACS Team
