### ISSUE TITLE
Wrong "M3_OOB_1" tags in test case

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#5]
Need to correct M3_OOB_1 tags in corresponding test case.

Definition of M3_OOB_1 

> For Level M3-based server systems, the IPMI out of band interface is not required. It is an implementation choice whether IPMI out-of-band is supported or not, and if supported, whether it is enabled or disabled by default.

**Comment by Guru9902** [comment]
@gtossk2 

#5

-M3_OOB_1 is related to IPMI, however in the ACS, we have wrongly tagged redfish OOB tests with it, So the tag is removed.

https://github.com/ARM-software/sbmr-acs/pull/12
