### ISSUE TITLE
Add "OSBootStarted" state in boot_table_redfish

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#6]
Systems might support "OSBootStarted" state in Redfish Boot Progress types [1].

[1] https://redfish.dmtf.org/schemas/v1/ComputerSystem.v1_21_0.json

**Comment by Guru9902** [comment]
https://github.com/ARM-software/sbmr-acs/pull/10

- OSBootStarted state added to boot_progress in boot_table_redfish.json as in some of the BMC implementation "OSBootStarted" is used as boot progress code to indicate the server is turned on hence updated the json
accordingly
